/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ACard: typeof import('./../src/ui/atoms/a-card.vue')['default']
    AContainer: typeof import('./../src/ui/atoms/a-container.vue')['default']
    AInput: typeof import('./../src/ui/atoms/a-input.vue')['default']
    AModal: typeof import('./../src/ui/atoms/a-modal.vue')['default']
    AppHeader: typeof import('./../src/ui/components/app-header/app-header.vue')['default']
    AppPage: typeof import('./../src/ui/components/app-page/app-page.vue')['default']
    ATable: typeof import('./../src/ui/atoms/a-table.vue')['default']
    ATableHead: typeof import('./../src/ui/atoms/a-table/a-table-head.vue')['default']
    ATableRow: typeof import('./../src/ui/atoms/a-table/a-table-row.vue')['default']
    BackButton: typeof import('./../src/ui/components/buttons/back-button.vue')['default']
    ClockInput: typeof import('./../src/ui/components/clock-input/clock-input.vue')['default']
    ClockInputHours: typeof import('./../src/ui/components/punch-clock/clock-input-hours.vue')['default']
    EmployeeInfo: typeof import('./../src/ui/views/employee/components/employee-info.vue')['default']
    EmployeeList: typeof import('./../src/ui/views/employee/components/employee-list.vue')['default']
    EmployeeMonthlyReport: typeof import('./../src/ui/components/employee-monthly-report/employee-monthly-report.vue')['default']
    EmployeePuchClock: typeof import('./../src/ui/views/employee/components/employee-puch-clock.vue')['default']
    EmployeesList: typeof import('./../src/ui/components/employees-list/employees-list.vue')['default']
    'EmployeesList-': typeof import('./../src/ui/views/employees/components/employees-list-.vue')['default']
    EmployeeTimeRecord: typeof import('./../src/ui/views/employee/components/employee-time-record.vue')['default']
    EmployeeTimeRecords: typeof import('./../src/ui/views/employee/components/employee-time-records.vue')['default']
    EmployerAddEmployeeModal: typeof import('./../src/ui/views/employer/components/employer-add-employee-modal.vue')['default']
    EmployerEmployeeDetails: typeof import('./../src/ui/views/employer/components/employer-employee-details.vue')['default']
    EmployerEmployeeList: typeof import('./../src/ui/views/employer/components/employer-employee-list.vue')['default']
    EmployerEmployeesList: typeof import('./../src/ui/views/employer/components/employer-employees-list.vue')['default']
    EmployerTabs: typeof import('./../src/ui/views/employer/components/employer-tabs.vue')['default']
    EmployerToolbar: typeof import('./../src/ui/views/employer/components/employer-toolbar.vue')['default']
    PuchClockActions: typeof import('./../src/ui/components/punch-clock/puch-clock-actions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgClose: typeof import('./../src/ui/components/svg/svg-close.vue')['default']
    SvgLogo: typeof import('./../src/ui/components/svg/svg-logo.vue')['default']
    SvgMaintenance: typeof import('./../src/ui/components/svg/svg-maintenance.vue')['default']
    SvgMenu: typeof import('./../src/ui/components/svg/svg-menu.vue')['default']
    SvgShield: typeof import('./../src/ui/components/svg/svg-shield.vue')['default']
    Tabs: typeof import('./../src/ui/views/employer/components/tabs.vue')['default']
  }
}
